# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d48b4cc2c51a588514f01513f996e76b78ca482159811a77adee53777e1c37394c2732991cdc9bd12efe8b5ee9ae01561a6c2e539770566444a891c152f5ec37

test:
  secret_key_base: bcd9c7201a81d93f1fa38b989334781bc9583958f2121ad5d1f005f93728a56ec9f3e113f63342b9ab175df56ef1155c8b7e8c0324946d428f5472c4ff2a40dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
